### ISSUE TITLE
Remaining TODOs

### ISSUE THREAD

**Issue by abstractalgo** [abstractalgo/ext-react#8]
Moving this from the README into an issue.

---

(also to allow TS to load files outside root scope)

(record a video walkthrough)

communication between background, popup and content scripts. typescript everywhere (@types/chrome).

(recipes: monorepo. shared lib.)

caveats: assets.

---

### todo

- [ ] working example extension
- [ ] shared folders (+monorepo)
- **browsers**
  - [x] chromium (v3 manifest)
  - [ ] firefox (v3 manifest ~~v2~~)
  - [ ] safari (?)
- **dev tools**
  - [ ] dev pipeline (watcher, hot reload, incremental builds, sim tabs env)
- **logic**
  - [ ] cross-context communication
    - [ ] storage
      - [ ] options / config
      - [ ] per tab
      - [ ] shared
      - [ ] synced
    - [ ] static assets

**Comment by joshsmith** [comment]
What needs done here to help with the dev pipeline aspect?

**Comment by abstractalgo** [comment]
I was mostly thinking about if there's a way to automate hot-reload in the browser and somehow see all the logs in the same places and make them easily reachable.

Currently, working on any of the React apps as regular React apps is totally fine, you should have no problems with that. But testing the entire project as a browser extension, by manually having to reload the extension, opening "Inspect views" etc is just quite tedious. I still don't have concrete ideas on how to achieve many of these, but it is something to consider.

**Comment by joshsmith** [comment]
The basic ideas behind [`web-ext-webpack-plugin`](https://github.com/hiikezoe/web-ext-webpack-plugin/blob/master/index.js) could be adapted outside webpack.

**Comment by joshsmith** [comment]
See the Extension Workshop [reference to `webext`](https://extensionworkshop.com/documentation/develop/#test-and-debug):

> You can use [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) to automatically install and update your extension while making coding changes.

Repurposing the webpack code into a different build process seems fairly straightforward.

**Comment by abstractalgo** [comment]
Thanks for sharing these!

I haven't spent too much time with these as, as far as I know, `web-ext` is Firefox-only. And this repo is aimed at manifest v3 which is still not supported by Firefox, so due to those mismatches, I didn't dig deep.

However, `web-ext-webpack-plugin` seems to mention Chromium capabilities as well, which is curious.

If you would like to spend some time with it and try to fit it into this repo's setup, that'd be amazing! Otherwise, I'll give it a shot, but can't guarantee when will that happen. Cheers!
